version: "3.8"

services:
  banner-shift:
    build:
      context: .
      dockerfile: Dockerfile
    image: banner-shift
    container_name: banner-shift
    ports:
      - "8080:8080"
    networks:
      - banner-shift-net

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - banner-shift-net
    restart: always

networks:
  banner-shift-net:
    driver: "bridge"
