env: local # local, dev, prod
http_server:
  address: banner-shift:8080
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  db: postgres
redis:
  addr: redis:6379
  user: user
  password: ""
  db: 0
  protocol: 3