env: "local" # local, dev, prod
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
postgres:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "postgres"
  db: "postgres"